/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
        roboto: ['Roboto', 'system-ui', 'sans-serif'],
        montserrat: ['Montserrat', 'system-ui', 'sans-serif'],
      },
      colors: {
        purple: {
          50: 'var(--color-purple-50)',
          100: 'var(--color-purple-100)',
          200: 'var(--color-purple-200)',
          300: 'var(--color-purple-300)',
          400: 'var(--color-purple-400)',
          500: 'var(--color-purple-500)',
          600: 'var(--color-purple-600)',
          700: 'var(--color-purple-700)',
          800: 'var(--color-purple-800)',
          900: 'var(--color-purple-900)',
          950: 'var(--color-purple-950)',
          accent: 'var(--color-purple-accent)',
          light: 'var(--color-purple-light)',
          lightest: 'var(--color-purple-lightest)',
          extra: {
            1: 'var(--color-purple-extra-1)',
            2: 'var(--color-purple-extra-2)',
            3: 'var(--color-purple-extra-3)',
            4: 'var(--color-purple-extra-4)',
            5: 'var(--color-purple-extra-5)',
            6: 'var(--color-purple-extra-6)',
            7: 'var(--color-purple-extra-7)',
            8: 'var(--color-purple-extra-8)',
            9: 'var(--color-purple-extra-9)',
            10: 'var(--color-purple-extra-10)',
          },
        },

        mauve: {
          50: 'var(--color-mauve-50)',
          100: 'var(--color-mauve-100)',
          200: 'var(--color-mauve-200)',
          300: 'var(--color-mauve-300)',
          400: 'var(--color-mauve-400)',
          500: 'var(--color-mauve-500)',
          600: 'var(--color-mauve-600)',
          700: 'var(--color-mauve-700)',
          800: 'var(--color-mauve-800)',
          900: 'var(--color-mauve-900)',
          950: 'var(--color-mauve-950)',

          'extra-1': 'var(--color-mauve-extra-1)',
          'extra-2': 'var(--color-mauve-extra-2)',
          'extra-3': 'var(--color-mauve-extra-3)',
          'extra-4': 'var(--color-mauve-extra-4)',
          'extra-5': 'var(--color-mauve-extra-5)',
          'extra-6': 'var(--color-mauve-extra-6)',
          'extra-7': 'var(--color-mauve-extra-7)',
          'extra-8': 'var(--color-mauve-extra-8)',
          'extra-9': 'var(--color-mauve-extra-9)',
          'extra-10': 'var(--color-mauve-extra-10)',
          'extra-11': 'var(--color-mauve-extra-11)',
          'extra-12': 'var(--color-mauve-extra-12)',
          'extra-13': 'var(--color-mauve-extra-13)',
          'extra-14': 'var(--color-mauve-extra-14)',
          'extra-15': 'var(--color-mauve-extra-15)',

          1: 'var(--color-mauve-1)',
          2: 'var(--color-mauve-2)',
          3: 'var(--color-mauve-3)',
          4: 'var(--color-mauve-4)',
          5: 'var(--color-mauve-5)',
          6: 'var(--color-mauve-6)',
          7: 'var(--color-mauve-7)',
          8: 'var(--color-mauve-8)',
          9: 'var(--color-mauve-9)',
          10: 'var(--color-mauve-10)',
          11: 'var(--color-mauve-11)',
        },

        'mauve-alpha': {
          1: 'var(--color-mauve-alpha-1)',
          2: 'var(--color-mauve-alpha-2)',
          3: 'var(--color-mauve-alpha-3)',
          4: 'var(--color-mauve-alpha-4)',
          5: 'var(--color-mauve-alpha-5)',
          6: 'var(--color-mauve-alpha-6)',
          7: 'var(--color-mauve-alpha-7)',
          8: 'var(--color-mauve-alpha-8)',
          9: 'var(--color-mauve-alpha-9)',
          10: 'var(--color-mauve-alpha-10)',
          11: 'var(--color-mauve-alpha-11)',
          12: 'var(--color-mauve-alpha-12)',
          13: 'var(--color-mauve-alpha-13)',
          14: 'var(--color-mauve-alpha-14)',
          15: 'var(--color-mauve-alpha-15)',
        },

        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
